# Generated by Django 3.0.2 on 2020-02-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackgroup',
            options={'verbose_name': 'FeedbackGroup', 'verbose_name_plural': 'FeedbackGroups'},
        ),
        migrations.AlterModelOptions(
            name='feedbackgroupsuser',
            options={'verbose_name': 'FeedbackGroupsUser', 'verbose_name_plural': 'FeedbackGroupsUsers'},
        ),
        migrations.AlterModelOptions(
            name='feedbackrequest',
            options={'verbose_name': 'FeedbackRequest', 'verbose_name_plural': 'FeedbackRequests'},
        ),
        migrations.AlterModelOptions(
            name='feedbackresponse',
            options={'verbose_name': 'FeedbackResponse', 'verbose_name_plural': 'FeedbackResponses'},
        ),
    ]
