# Generated by Django 3.0.2 on 2020-02-09 01:40

from django.db import migrations, models
import howsmytrack.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackrequest',
            name='media_type',
            field=models.CharField(choices=[(howsmytrack.core.models.MediaTypeChoice['SOUNDCLOUD'], 'Soundcloud'), (howsmytrack.core.models.MediaTypeChoice['GOOGLEDRIVE'], 'Google Drive'), (howsmytrack.core.models.MediaTypeChoice['DROPBOX'], 'Dropbox')], max_length=32),
        ),
    ]
