# Generated by Django 3.0.2 on 2020-02-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200209_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackgroup',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='media_type',
            field=models.CharField(choices=[('SOUNDCLOUD', 'Soundcloud'), ('GOOGLEDRIVE', 'Google Drive'), ('DROPBOX', 'Dropbox')], max_length=32),
        ),
    ]
