# Generated by Django 3.0.3 on 2020-02-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200210_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='email_when_grouped',
            field=models.BooleanField(default=False),
        ),
    ]
