# Generated by Django 3.0.2 on 2020-02-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedbackrequest_email_when_grouped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='media_type',
            field=models.CharField(choices=[('SOUNDCLOUD', 'Soundcloud'), ('GOOGLEDRIVE', 'Google Drive'), ('DROPBOX', 'Dropbox'), ('ONEDRIVE', 'OneDrive')], max_length=32),
        ),
    ]
