# Generated by Django 3.0.2 on 2020-02-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200215_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackrequest',
            name='media_url',
            field=models.CharField(max_length=255),
        ),
    ]
