# Generated by Django 3.0.2 on 2020-02-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_feedbackrequest_reminder_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='genre',
            field=models.CharField(choices=[('ELECTRONIC', 'Electronic'), ('HIPHOP', 'Hip-Hop/Rap'), ('NO_GENRE', 'No Genre')], default='NO_GENRE', max_length=32),
        ),
    ]
