# Generated by Django 3.0.2 on 2020-03-11 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200303_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='allow_replies',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FeedbackResponseReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('allow_replies', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('feedback_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.FeedbackResponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.FeedbackGroupsUser')),
            ],
            options={
                'verbose_name': 'FeedbackResponseReply',
                'verbose_name_plural': 'FeedbackResponseReplies',
            },
        ),
    ]
