# Generated by Django 3.0.3 on 2020-03-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200311_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponsereply',
            name='time_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
