# Generated by Django 3.0.2 on 2020-03-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_feedbackresponsereply_time_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackrequest',
            name='genre',
            field=models.CharField(blank=True, choices=[('ELECTRONIC', 'Electronic'), ('HIPHOP', 'Hip-Hop/Rap'), ('JAZZ', 'Jazz'), ('URBAN_RNB', 'Urban/R&B'), ('POP', 'Pop'), ('ROCK_METAL_PUNK', 'Rock/Metal/Punk'), ('NO_GENRE', 'No Genre')], default='NO_GENRE', max_length=32, null=True),
        ),
    ]
