# Generated by Django 3.0.3 on 2020-03-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200314_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackgroupsuser',
            name='send_reminder_emails',
            field=models.BooleanField(default=True),
        ),
    ]
