# Generated by Django 3.0.2 on 2020-01-31 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackGroupsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soundcloud_url', models.CharField(max_length=100)),
                ('feedback_prompt', models.TextField()),
                ('feedback_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='feedbackgroups.FeedbackGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='feedbackgroups.FeedbackGroupsUser')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.BooleanField()),
                ('feedback_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='feedbackgroups.FeedbackRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='feedbackgroups.FeedbackGroupsUser')),
            ],
        ),
    ]
