# Generated by Django 3.0.2 on 2020-01-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackgroups', '0003_auto_20200131_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackgroupsuser',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='feedback_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
